version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_movies
    env_file:
      - ./config/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    networks:
      - movies_network

  django:
    build:
      context: movies_admin
      dockerfile: Dockerfile
    container_name: django_movies
    volumes:
      - static_volume:/data/static
    networks:
      - movies_network
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres
    env_file: ./config/.env

  nginx:
    image: nginx:1.19.2
    container_name: nginx_movies
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/data:ro
    ports:
      - "8000:8000"
      - "80:80"
    networks:
      - movies_network
    depends_on:
      - django

  elastic:
    # image: elasticsearch:7.7.0  # Requires much less memory
    image: elasticsearch:7.14.0
    container_name: elastic_movies
    environment:
      - discovery.type=single-node
#    ports:
#      - "9200:9200"
    networks:
      - movies_network
    depends_on:
      - postgres
    volumes:
      - es_data:/usr/share/elasticsearch/data

  etl:
    build:
      context: postgres_to_es
      dockerfile: Dockerfile
    container_name: etl_movies
    volumes:
      - ./postgres_to_es:/code
    networks:
      - movies_network
    command: python etl.py
    depends_on:
      - postgres
      - elastic
    env_file:
      - ./config/.env

  redis:
    build:
      context: redis
      dockerfile: Dockerfile
    container_name: redis_movies
    volumes:
      - ./redis/conf/etc:/usr/local/etc/redis
      - redis_data:/data
#    ports:
#      - "6379:6379"
    networks:
      - movies_network
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]


  fast_api:
    build:
      context: fast_api
      dockerfile: Dockerfile
    container_name: fast_api_movies
    volumes:
      - ./fast_api:/fast_api:ro
    networks:
      - movies_network
    depends_on:
      - elastic
      - redis
    env_file:
      - ./config/.env
    command: ["python", "main.py"]

volumes:
  es_data:
  redis_data:
  static_volume:

networks:
  movies_network:
