swagger: "2.0"
info:
  version: "1.0.0"
  title: "Сервис Assistant"
  description: "Поиск информации о фильмах"
basePath: "/api/v1/bob/"
tags:
- name: "Movies"
  description: "Поиск информации о фильмах"
schemes:
- "http"
paths:
  /:
    get:
      summary: "Контроллер вызывает запрошенный метод класса SearchConnector"
      description: "Пробует вызвать метод класса SearchConnector, проверяет есть ли такой метод, если есть вызывает и возвращает результат"
      operationId: "Search"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: query
        name: "method"
        description: "Метод который хотим вызвать, например: find_film_directors"
        required: true
        schema:
          type: "string"
      - in: query
        name: "query"
        description: "Строка запроса, например: новая надежда"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK, информация в виде JSON"
          content:
            application/json:
              schema:
                type: object
        "400":
          description: "BAD REQUEST, нехватает необходимых параметров"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "404":
          description: "NOT FOUND, по указанным ключевым словам ничего найти не удалось"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "501":
          description: "NOT IMPLEMENTED, данный метод не реализован в классе поиска"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    # Schema for error response body
    Error:
      type: object
      properties:
        error:
          type: 'string'